// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5P1UelogsSpR2poWOLgHbLYcPOF5QEvw',
    appId: '1:474484831866:web:7f4b96c1358d5c59c3edc3',
    messagingSenderId: '474484831866',
    projectId: 'mcs-management',
    authDomain: 'mcs-management.firebaseapp.com',
    storageBucket: 'mcs-management.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiPWzg_Y_SFva6ftwj3JmJXD9qFQcZU3Q',
    appId: '1:474484831866:android:58d93344181273a0c3edc3',
    messagingSenderId: '474484831866',
    projectId: 'mcs-management',
    storageBucket: 'mcs-management.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5P1UelogsSpR2poWOLgHbLYcPOF5QEvw',
    appId: '1:474484831866:web:eea46bf5ba281813c3edc3',
    messagingSenderId: '474484831866',
    projectId: 'mcs-management',
    authDomain: 'mcs-management.firebaseapp.com',
    storageBucket: 'mcs-management.firebasestorage.app',
  );
}
